<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="7" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-14T08:01:07 IST" name="Surefire suite" finished-at="2024-02-14T08:04:13 IST" duration-ms="186186">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.LoginErrorValidation()[pri:0, instance:Amazon.Frameworkdesign.tests.ErrorValidationsTest@5dd6264]" name="LoginErrorValidation" class="Amazon.Frameworkdesign.tests.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:cucumber.TestNGTestRunner@7f552bd3]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
      <group name="purchase">
        <method signature="ErrorValidationsTest.ProductErrorValidation(java.util.HashMap)[pri:0, instance:Amazon.Frameworkdesign.tests.ErrorValidationsTest@5dd6264]" name="ProductErrorValidation" class="Amazon.Frameworkdesign.tests.ErrorValidationsTest"/>
      </group> <!-- purchase -->
    </groups>
    <test started-at="2024-02-14T08:01:07 IST" name="Surefire test" finished-at="2024-02-14T08:04:13 IST" duration-ms="186186">
      <class name="Amazon.Frameworkdesign.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Amazon.Frameworkdesign.tests.SubmitOrderTest@4690b489]" started-at="2024-02-14T08:02:55 IST" name="launchApplication" finished-at="2024-02-14T08:03:10 IST" duration-ms="15560" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder()[pri:0, instance:Amazon.Frameworkdesign.tests.SubmitOrderTest@4690b489]" started-at="2024-02-14T08:03:10 IST" name="SubmitOrder" finished-at="2024-02-14T08:03:25 IST" duration-ms="14267" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Amazon.Frameworkdesign.tests.SubmitOrderTest@4690b489]" started-at="2024-02-14T08:03:25 IST" name="tearDown" finished-at="2024-02-14T08:03:25 IST" duration-ms="341" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Amazon.Frameworkdesign.tests.SubmitOrderTest@4690b489]" started-at="2024-02-14T08:03:25 IST" name="launchApplication" finished-at="2024-02-14T08:03:41 IST" duration-ms="15509" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:Amazon.Frameworkdesign.tests.SubmitOrderTest@4690b489]" started-at="2024-02-14T08:03:41 IST" name="OrderHistoryTest" finished-at="2024-02-14T08:03:41 IST" depends-on-methods="Amazon.Frameworkdesign.tests.SubmitOrderTest.SubmitOrder" duration-ms="597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Amazon.Frameworkdesign.tests.SubmitOrderTest@4690b489]" started-at="2024-02-14T08:03:41 IST" name="tearDown" finished-at="2024-02-14T08:03:41 IST" duration-ms="149" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Amazon.Frameworkdesign.tests.SubmitOrderTest -->
      <class name="Amazon.Frameworkdesign.tests.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Amazon.Frameworkdesign.tests.ErrorValidationsTest@5dd6264]" started-at="2024-02-14T08:01:07 IST" name="launchApplication" finished-at="2024-02-14T08:01:24 IST" duration-ms="17442" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:Amazon.Frameworkdesign.tests.ErrorValidationsTest@5dd6264]" started-at="2024-02-14T08:01:24 IST" name="LoginErrorValidation" finished-at="2024-02-14T08:01:25 IST" duration-ms="1201" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login Successfully] but found [Login Successfully1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login Successfully] but found [Login Successfully1]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Amazon.Frameworkdesign.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Amazon.Frameworkdesign.tests.ErrorValidationsTest@5dd6264]" started-at="2024-02-14T08:01:25 IST" name="tearDown" finished-at="2024-02-14T08:01:25 IST" duration-ms="142" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Amazon.Frameworkdesign.tests.ErrorValidationsTest@5dd6264]" started-at="2024-02-14T08:01:25 IST" name="launchApplication" finished-at="2024-02-14T08:01:41 IST" duration-ms="15459" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:Amazon.Frameworkdesign.tests.ErrorValidationsTest@5dd6264]" started-at="2024-02-14T08:01:41 IST" name="LoginErrorValidation" finished-at="2024-02-14T08:01:41 IST" duration-ms="534" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login Successfully] but found [Login Successfully1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login Successfully] but found [Login Successfully1]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Amazon.Frameworkdesign.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Amazon.Frameworkdesign.tests.ErrorValidationsTest@5dd6264]" started-at="2024-02-14T08:01:41 IST" name="tearDown" finished-at="2024-02-14T08:01:42 IST" duration-ms="133" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Amazon.Frameworkdesign.tests.ErrorValidationsTest@5dd6264]" started-at="2024-02-14T08:01:42 IST" name="launchApplication" finished-at="2024-02-14T08:01:57 IST" duration-ms="15415" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation(java.util.HashMap)[pri:0, instance:Amazon.Frameworkdesign.tests.ErrorValidationsTest@5dd6264]" started-at="2024-02-14T08:01:57 IST" name="ProductErrorValidation" data-provider="getData" finished-at="2024-02-14T08:02:11 IST" duration-ms="13493" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=@Sairam01@, product=ZARA COAT 3, email=anandsharma379@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Amazon.Frameworkdesign.tests.ErrorValidationsTest@5dd6264]" started-at="2024-02-14T08:02:11 IST" name="tearDown" finished-at="2024-02-14T08:02:11 IST" duration-ms="113" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Amazon.Frameworkdesign.tests.ErrorValidationsTest@5dd6264]" started-at="2024-02-14T08:02:11 IST" name="launchApplication" finished-at="2024-02-14T08:02:41 IST" duration-ms="30350" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation(java.util.HashMap)[pri:0, instance:Amazon.Frameworkdesign.tests.ErrorValidationsTest@5dd6264]" started-at="2024-02-14T08:02:41 IST" name="ProductErrorValidation" data-provider="getData" finished-at="2024-02-14T08:02:55 IST" duration-ms="13489" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Iamking@000, product=ADIDAS ORIGINAL, email=anshika@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Amazon.Frameworkdesign.tests.ErrorValidationsTest@5dd6264]" started-at="2024-02-14T08:02:55 IST" name="tearDown" finished-at="2024-02-14T08:02:55 IST" duration-ms="144" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Amazon.Frameworkdesign.tests.ErrorValidationsTest -->
      <class name="cucumber.TestNGTestRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:cucumber.TestNGTestRunner@7f552bd3]" started-at="2024-02-14T08:03:41 IST" name="setUpClass" finished-at="2024-02-14T08:03:42 IST" duration-ms="523" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@b55f5b7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:cucumber.TestNGTestRunner@7f552bd3]" started-at="2024-02-14T08:03:42 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-02-14T08:04:13 IST" duration-ms="30955" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Positive Test of Submitting the order"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Purchase the order from Ecommerce Website"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null
at AmazonFrameworkdesign.pageobjects.ProductCatalogue.addProductToCart(ProductCatalogue.java:56)
at AmazonFrameworkdesign.stepDefinition.StepDefinitionImpl.I_add_product_to_cart(StepDefinitionImpl.java:45)
at ✽.I add product "ZARA COAT 3" to Cart(file:///C:/Users/ANAND%20SHARMA/eclipse-workspace/Frameworkdesign/src/test/java/cucumber/SubmitOrder.feature:13)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:cucumber.TestNGTestRunner@7f552bd3]" started-at="2024-02-14T08:04:13 IST" name="tearDownClass" finished-at="2024-02-14T08:04:13 IST" duration-ms="29" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- cucumber.TestNGTestRunner -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
